### ISSUE TITLE
Office

### ISSUE THREAD

**Issue by SheepTester** [briarsychung/tech_guy#16]
> btw @SheepTester just so u know how the office / computer works
when u summon, the student gets added to the queue
of students in office
when u click office
u are essentially moving away form ur computer to ur office space
in so the first in line will be there
and u can search their backpack
aka, take stuff out and put stuff in
a la papers please
then u can release or suspend
then next student comes in
at end of school day everyone auto leaves

(I asked, "is there a place to store items you take out?")
> ur desk ya
itll be like
a drag and drop
with desk / packpack

(I commented, "lol out in the open")
> ofc ofc
full transparency

**Comment by briarsychung** [comment]
I'll make it this weekend

**Comment by briarsychung** [comment]
Idk where your edits are at for the cocnept designs so I think I'll just use the old version I made to base off the office, hopefully it's easy to carry over your changes.

**Comment by SheepTester** [comment]
Epic; it's in cocnept-designs/sean/responsive.html but I think I can just manually reapply the changes
