### ISSUE TITLE
Abstractify the dialogue

### ISSUE THREAD

**Issue by SheepTester** [briarsychung/tech_guy#18]
Currently, the intro box thing and the principal introduction that floats over the UI use almost the same code, but yet they're different

Ideally:

- [x] Make a new JS file that can be easily imported
- [x] Use Brandon style
- [x] An option to not measure the height of the thing (for the floating over UI thing)
- [x] Be able to specify the image and background colour in the JSON
  - The image paths won't resolve themselves though. I think it could reference an image ID whose mappings to the actual image URL/object can be given separately
- [x] Update existing demos accordingly

**Comment by briarsychung** [comment]
I think the main thing for continuity for style is button padding, font size, and overall whitespace / padding. Also, we might have different sounds for different people so might have to be in the JSON as well.

**Comment by SheepTester** [comment]
I think that's a CSS thing; we probably should make a CSS file with some basic styles so it's more universal and consistent

**Comment by briarsychung** [comment]
Yeah, until today the CSS was all in the HTML lol.
