### ISSUE TITLE
Enable Github pages

### ISSUE THREAD

**Issue by SheepTester** [briarsychung/tech_guy#2]
Expectation: https://anematode.github.io/tech_guy/ works

Reality: Expectations did not happen

Reproduction:

1. Go to https://anematode.github.io/tech_guy/

**Comment by briarsychung** [comment]
we'd like this to be on moomath.

**Comment by SheepTester** [comment]
but it could be temporarily on until it's on moomath

**Comment by briarsychung** [comment]
we should also spam sheeptester ads on it (Or vice versa, put it on sheeptester and spam ads to moomath)

**Comment by SheepTester** [comment]
epic github pages EXISTS
