### ISSUE TITLE
randomlyRound is not implemented correctly

### ISSUE THREAD

**Issue by SheepTester** [briarsychung/tech_guy#21]
https://github.com/anematode/tech_guy/blob/76b1bb0a4f680dd68e3ae994e79c0fb4b1e7c53a/school/school.js#L101-L107

Chances are, if r is greater than 1, it'll always round up

I think we knew it was flawed from [the beginning](https://github.com/anematode/tech_guy/commit/07382ab906a35983efdce84eab47ea694e318f28#r34933283)

@heaucques

**Comment by briarsychung** [comment]
Changing `Math.trunc(r)` to `+('.'+(r + '').split('.')[1])` should fix it? Oh wait, I can't read, or `r-Math.trunc(r)` as was already suggested.

**Comment by SheepTester** [comment]
Why not just do `r % 1`? Does it need to work with negative numbers? (though `r - Math.trunc(r)` wouldn't work for negative numbers either)

**Comment by briarsychung** [comment]
Whatever, it's fixed lol
