### ISSUE TITLE
Manual panning

### ISSUE THREAD

**Issue by SheepTester** [briarsychung/tech_guy#33]
Autopanning is kind of slow; maybe people should be able to take over?

**Comment by briarsychung** [comment]
Autopanning will mess with selecting too

**Comment by SheepTester** [comment]
> Autopanning will mess with selecting too

Not really if selecting is just clicking; there could be a threshold for dragging, and mouse users can use scroll wheel to weeeee

**Comment by briarsychung** [comment]
Nah cuz if there is a lot of students, and they are moving, and the camera is autopanning, I could see it being really hard to select the right one. Also idk why autopanning is better than manual especially for mouse where it's more intuitive to only pan when the mouse goes near the edge.

Additionally, it would be annoying if someone was to select a student but the camera pans away, and the student leaves the frame.
