### ISSUE TITLE
Tab focus ring

### ISSUE THREAD

**Issue by SheepTester** [briarsychung/tech_guy#40]
Since we're doing the forbidden

```css
:focus {
    outline: none;
}
```

we should still show tab focus for those who prefer using the tab key. There's [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) but it's [a bit too new](https://caniuse.com/#search=focus-visible)

We could use the [polyfill](https://github.com/WICG/focus-visible) or use the [one I've been using](https://github.com/Orbiit/elimination/blob/master/js/tab-key-focus.js)

**Comment by briarsychung** [comment]
We could just change the outline color; the blue felt out of place.

**Comment by SheepTester** [comment]
Meh I don't like the outline appearing for mouse users lol

**Comment by briarsychung** [comment]
True true. Also, who would use tab for a point and click game???? (I purposely made the gui click-only)

**Comment by SheepTester** [comment]
idk but the web has standards!

**Comment by briarsychung** [comment]
people are wack
r we also gonna check for old browsers too then cuz thatll be a pain

**Comment by SheepTester** [comment]
meh nah
