### ISSUE TITLE
Create sprites in a web worker

### ISSUE THREAD

**Issue by SheepTester** [briarsychung/tech_guy#47]
Creating student data is also a bit slow, but this issue only focuses on sprite images

I think we can transform sprite.js to manually place down pixels instead of using `drawImage` (because OffscreenCanvas is not supported on Safari). ImageData objects can be sent to and from web workers, which is great.

I propose:

1. On the page, it loads and converts all necessary images to ImageData objects using a canvas.
2. It creates a web worker and sends it all the ImageData objects.
3. Whenever it needs to create a batch of students, it'll send over the student information and it'll come back with a bunch of ImageData objects which can then be stored inside a SpriteCache

**Comment by briarsychung** [comment]
For me it takes about 2 seconds to create everything, which I think is fine; if you want to optimize it tho there's obv no harm in that.

**Comment by SheepTester** [comment]
Epic
